- name:  parameters store in aws
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: create/update the parameters store in aws
      community.aws.aws_ssm_parameter_store:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: us-east-1
      loop:
        - { name: "dev.cart.REDIS_HOST", value: "redis-dev.chandupcs.online" }
        - { name: "dev.cart.CATALOGUE_HOST", value: "catalogue-dev.chandupcs.online" }
        - { name: "dev.cart.CATALOGUE_PORT", value: "80" }
        - { name: "dev.catalogue.MONGO", value: "true" }
        - { name: "dev.catalogue.MONGO_URL", value: "mongodb://mongodb-dev.chandupcs.online:27017/catalogue" }
        - { name: "MONGO_URL", value: "mongodb://mongodb-dev.chandupcs.online:27017/catalogue" }
        - { name: "dev.frontend.CATALOGUE_URL", value: "http://catalogue-dev.chandupcs.online:80/" }
        - { name: "dev.frontend.CART_URL", value: "http://cart-dev.chandupcs.online:80/" }
        - { name: "dev.frontend.USER_URL", value: "http://user-dev.chandupcs.online:80/" }
        - { name: "dev.frontend.PAYMENT_URL", value: "http://payment-dev.chandupcs.online:80/" }
        - { name: "dev.frontend.SHIPPING_URL", value: "http://shipping-dev.chandupcs.online:80/" }
        - { name: "dev.payment.CART_HOST", value: "cart-dev.chandupcs.online" }
        - { name: "dev.payment.USER_HOST", value: "user-dev.chandupcs.online" }
        - { name: "dev.payment.CART_PORT", value: "80" }
        - { name: "dev.payment.USER_PORT", value: "80" }
        - { name: "dev.payment.AMQP_HOST", value: "rabbitmq-dev.chandupcs.online" }
        - { name: "dev.payment.AMQP_USER", value: "roboshop" }
        - { name: "dev.shipping.CART_ENDPOINT", value: "cart-dev.chandupcs.online:80" }
        - { name: "dev.shipping.DB_HOST", value: "mysql-dev.chandupcs.online" }
        - { name: "dev.user.MONGO", value: "true" }
        - { name: "dev.user.MONGO_URL", value: "mongodb://mongodb-dev.chandupcs.online:27017/users" }
        - { name: "dev.user.REDIS_HOST", value: "redis-dev.chandupcs.online" }
        - { name: "sonarqube.user", value: "admin" }
        - { name: "sonarqube.pass", value: "admin123" }

        
### PASSWORDS SHOULD NEVER BE KEPT IN THESE REPOS, THOSE SHOULD BE CREATED MAUALLY, BUT FOR LAB PURPOSE IAM CREATING HERE
    - name: Create Secrets
      community.aws.aws_ssm_parameter_store:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        region: us-east-1
        string_type: "SecureString"
      loop:
        - { name: "dev.payment.AMQP_PASS", value: "roboshop123" }
        - { name: "nexus.user", value: "admin" }
        - { name: "nexus.pass", value: "admin123" }
        - { name: "dev.mysql.mysql_password", value: "RoboShop@1" }
        - { name: "dev.rabbitmq.user", value: "roboshop123" }
        - { name: "dev.rabbitmq.password", value: "roboshop123" }
        - { name: "dev.shipping.mysql_password", value: "RoboShop@1" }
        - { name: "dev.docdb.user", value: "chandra" }
        - { name: "dev.docdb.password", value: "roboshop123" }
        - { name: "dev.rds.user", value: "chandra" }
        - { name: "dev.rds.password", value: "roboshop123" }
        - { name: "grafana.api_key", value: "eyJrIjoiVG04enA0aHpVSkJIQ1lYYk1XSW5nMmZraHRyN3lZR3YiLCJuIjoicm9ib3Nob3AiLCJpZCI6MX0=" }
        - { name: "ses.user", value: "AKIAS27NLJNM26IWJ4W6" }
        - { name: "ses.pass", value: "BNJM6/DxTxcwpjsNjq6co88S8evesHt1MbP4/VNhQKIi" }
        - { name: "dev-SSH.user", value: "root" }
        - { name: "dev-SSH.pass", value: "DevOps321" }




