- name: install nginx web sever
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: remove default old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: add html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

#- name: download {{component}} app content and extracting
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
#    dest: /usr/share/nginx/html
#    remote_src: yes


- name: Download {{component}} compiled App content
  ansible.builtin.unarchive:
    src: http://{{nexus_user}}:{{nexus_pass}}@172.31.17.214:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest:  /usr/share/nginx/html
    remote_src: yes
  vars:
    nexus_user: "{{ lookup('aws_ssm', 'nexus.user', region='us-east-1' ) }}"
    nexus_pass: "{{ lookup('aws_ssm', 'nexus.pass', region='us-east-1' ) }}"

- name: copy roboshop conf file
  ansible.builtin.template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/{{component}}.conf

- name: start and enable the nginx
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes




