- name: install nginx web sever
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: remove default old content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: add html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download {{component}} app content and extracting
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    path: /usr/share/nginx/html
    remote_src: yes

- name: copy roboshop conf file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/{{component}}.conf

- name: start and enable the nginx
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes




