- name: stop the application {{ component }}
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: stopped

- name: restart the task
  ansible.builtin.include_tasks: "app_pre_req.yml"


- name: start the application {{ component }}
  ansible.builtin.systemd:
    name: "{{ component }}"
    state: started
